export interface HttpStatus { code: number; name: string; zh: string }

export const HTTP_STATUSES: HttpStatus[] = [
  // 1xx Informational
  { code: 100, name: 'Continue', zh: '继续：服务器已收到请求头，客户端应继续发送请求体' },
  { code: 101, name: 'Switching Protocols', zh: '切换协议：服务器同意升级协议（如切换到 WebSocket）' },
  { code: 102, name: 'Processing', zh: '处理中：服务器已接受请求但尚未完成处理（WebDAV）' },
  { code: 103, name: 'Early Hints', zh: '早期提示：在最终响应前预先发送部分响应头以优化加载' },
  // 2xx Success
  { code: 200, name: 'OK', zh: '成功：请求已成功，返回请求的数据' },
  { code: 201, name: 'Created', zh: '已创建：请求成功且服务器创建了新资源' },
  { code: 202, name: 'Accepted', zh: '已接受：请求已接受但处理尚未完成（异步场景）' },
  { code: 203, name: 'Non-Authoritative Information', zh: '非权威信息：响应数据来自第三方副本而非源服务器' },
  { code: 204, name: 'No Content', zh: '无内容：请求成功但响应体为空（如 DELETE 操作）' },
  { code: 205, name: 'Reset Content', zh: '重置内容：请求成功，客户端应重置文档视图（如清空表单）' },
  { code: 206, name: 'Partial Content', zh: '部分内容：服务器成功处理了 Range 请求，用于断点续传' },
  // 3xx Redirection
  { code: 300, name: 'Multiple Choices', zh: '多种选择：请求资源存在多个可选响应，客户端需自行选择' },
  { code: 301, name: 'Moved Permanently', zh: '永久重定向：资源已永久移至新 URL，浏览器会更新书签' },
  { code: 302, name: 'Found', zh: '临时重定向：资源临时移至新 URL，后续仍用原 URL 访问' },
  { code: 303, name: 'See Other', zh: '查看其他：应使用 GET 方法访问另一个 URI（常用于 POST 后重定向）' },
  { code: 304, name: 'Not Modified', zh: '未修改：资源未变化，客户端应使用本地缓存版本' },
  { code: 307, name: 'Temporary Redirect', zh: '临时重定向：临时移至新 URL 且必须保持原 HTTP 方法不变' },
  { code: 308, name: 'Permanent Redirect', zh: '永久重定向：永久移至新 URL 且必须保持原 HTTP 方法不变' },
  // 4xx Client Errors
  { code: 400, name: 'Bad Request', zh: '错误请求：请求语法错误或参数无效，服务器无法理解' },
  { code: 401, name: 'Unauthorized', zh: '未授权：缺少有效的身份验证凭据，需要登录' },
  { code: 402, name: 'Payment Required', zh: '需要付款：保留状态码，用于数字支付场景（暂未标准化）' },
  { code: 403, name: 'Forbidden', zh: '禁止访问：身份已验证但无权访问该资源' },
  { code: 404, name: 'Not Found', zh: '未找到：请求的资源不存在于服务器上' },
  { code: 405, name: 'Method Not Allowed', zh: '方法不允许：该资源不支持当前使用的 HTTP 方法' },
  { code: 406, name: 'Not Acceptable', zh: '不可接受：服务器无法生成符合客户端 Accept 头的响应' },
  { code: 407, name: 'Proxy Authentication Required', zh: '代理认证必填：需要先通过代理服务器的身份验证' },
  { code: 408, name: 'Request Timeout', zh: '请求超时：服务器等待客户端请求超时' },
  { code: 409, name: 'Conflict', zh: '冲突：请求与服务器当前状态冲突（如并发修改或重复创建）' },
  { code: 410, name: 'Gone', zh: '已删除：请求的资源已永久删除且不会恢复' },
  { code: 411, name: 'Length Required', zh: '需要内容长度：请求缺少必需的 Content-Length 头' },
  { code: 412, name: 'Precondition Failed', zh: '前置条件失败：请求头中的条件（If-Match 等）不满足' },
  { code: 413, name: 'Content Too Large', zh: '请求体过大：请求实体超过服务器允许的大小限制' },
  { code: 414, name: 'URI Too Long', zh: 'URI 过长：请求 URI 超过服务器允许的最大长度' },
  { code: 415, name: 'Unsupported Media Type', zh: '不支持的媒体类型：服务器不支持请求体的 Content-Type' },
  { code: 416, name: 'Range Not Satisfiable', zh: '范围无法满足：Range 请求头指定的范围超出资源大小' },
  { code: 417, name: 'Expectation Failed', zh: '期望失败：服务器无法满足 Expect 请求头中的期望条件' },
  { code: 418, name: "I'm a Teapot", zh: '我是茶壶：愚人节玩笑状态码，茶壶拒绝煮咖啡（RFC 2324）' },
  { code: 421, name: 'Misdirected Request', zh: '请求被误导：请求发送到了无法产生响应的服务器' },
  { code: 422, name: 'Unprocessable Content', zh: '无法处理的内容：请求格式正确但语义错误，如表单验证失败' },
  { code: 425, name: 'Too Early', zh: '过早：服务器拒绝处理可能被重放的早期数据请求' },
  { code: 426, name: 'Upgrade Required', zh: '需要升级：客户端必须升级到指定协议才能继续' },
  { code: 428, name: 'Precondition Required', zh: '需要前置条件：服务器要求请求必须包含条件头（如 If-Match）' },
  { code: 429, name: 'Too Many Requests', zh: '请求过于频繁：客户端在单位时间内发送的请求超过限制' },
  { code: 431, name: 'Request Header Fields Too Large', zh: '请求头字段过大：请求头总长度或单个字段超过服务器限制' },
  { code: 451, name: 'Unavailable For Legal Reasons', zh: '因法律原因不可用：内容因法律限制（版权、审查等）无法提供' },
  // 5xx Server Errors
  { code: 500, name: 'Internal Server Error', zh: '服务器内部错误：服务器遇到意外情况无法完成请求' },
  { code: 501, name: 'Not Implemented', zh: '未实现：服务器不支持完成请求所需的功能或 HTTP 方法' },
  { code: 502, name: 'Bad Gateway', zh: '错误网关：网关或代理从上游服务器收到了无效响应' },
  { code: 503, name: 'Service Unavailable', zh: '服务不可用：服务器暂时过载或正在维护，稍后重试' },
  { code: 504, name: 'Gateway Timeout', zh: '网关超时：网关或代理等待上游服务器响应超时' },
  { code: 505, name: 'HTTP Version Not Supported', zh: '不支持的 HTTP 版本：服务器不支持请求中使用的 HTTP 协议版本' },
  { code: 506, name: 'Variant Also Negotiates', zh: '变体也在协商：服务器内容协商配置出现循环错误' },
  { code: 507, name: 'Insufficient Storage', zh: '存储空间不足：服务器无法存储完成请求所需的内容（WebDAV）' },
  { code: 508, name: 'Loop Detected', zh: '检测到循环：服务器在处理请求时检测到无限循环（WebDAV）' },
  { code: 510, name: 'Not Extended', zh: '未扩展：服务器需要请求进一步扩展才能处理' },
  { code: 511, name: 'Network Authentication Required', zh: '需要网络认证：客户端需要进行网络认证才能获得访问权限' },
]
